name:  Shell Commands

on: [push]

jobs:
  run-shell-commmand:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Ma, ya llegue"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Usamos Python
        run: |
          import platform
          print("Se corre en :" + platform.processor())
        shell: python
