name:  Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: trabajojs
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Eduardo Rojo"
      - name: Log del primer steps
        run: echo "{{ steps.trabajojs.outputs.time }}"