name:  Shell Commands

on: [push]

jobs:
  run-shell-commmand:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Ma, ya llegue"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Usamos Python
        run: |
          import platform
          print("Prueba de plataforma :" + platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: ['run-shell-commmand']
    steps:
      - name: Usamos PoweShell
        run: Get-Location
      - name: Usamos Bash
        run: pwd
        shell: bash
     
